FROM apache/airflow:2.9.3-python3.11

USER root
# Install git for dbt deps
RUN apt-get update \
  && apt-get install -y --no-install-recommends git \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /requirements.txt
RUN pip install --no-cache-dir dbt-bigquery "google-genai" "google-cloud-bigquery" "python-dotenv"
